# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# Copy the solution file and restore dependencies
COPY *.sln ./

# Copy project files for all necessary projects
COPY Emite.CCM.API/*.csproj ./Emite.CCM.API/
COPY Emite.CCM.Application/*.csproj ./Emite.CCM.Application/
COPY Emite.CCM.Infrastructure/*.csproj ./Emite.CCM.Infrastructure/
COPY Emite.Common.API/*.csproj ./Emite.Common.API/
COPY Emite.CCM.Core/*.csproj ./Emite.CCM.Core/
COPY Emite.CCM.Web/*.csproj ./Emite.CCM.Web/
COPY Emite.Common.Services.Shared/*.csproj ./Emite.Common.Services.Shared/
COPY Emite.Common.Utility/*.csproj ./Emite.Common.Utility/
COPY Emite.Common.Web.Utility/*.csproj ./Emite.Common.Web.Utility/
COPY Emite.Common.Core/*.csproj ./Emite.Common.Core/
COPY Emite.Common.Core.Base/*.csproj ./Emite.Common.Core.Base/
COPY Emite.Common.Data/*.csproj ./Emite.Common.Data/
COPY Emite.Common.Identity.Abstractions/*.csproj ./Emite.Common.Identity.Abstractions/
COPY Emite.CCM.EmailSending/*.csproj ./Emite.CCM.EmailSending/
COPY Emite.CCM.ExcelProcessor/*.csproj ./Emite.CCM.ExcelProcessor/
COPY Emite.CCM.Scheduler/*.csproj ./Emite.CCM.Scheduler/
COPY Emite.CCM.ChatGPT/*.csproj ./Emite.CCM.ChatGPT/
COPY Emite.CCM.UnitTest/*.csproj ./Emite.CCM.UnitTest/

# Restore all dependencies for the solution
RUN dotnet restore

# Copy all the project files
COPY . .

# Build the API project
WORKDIR /source/Emite.CCM.Web
RUN dotnet publish -c Release -o /app

# Stage 2: Run Migrations and Publish using SDK Image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration
WORKDIR /app

# Copy the build output
COPY --from=build /app ./

# Install dotnet-ef tool to run migrations
RUN dotnet tool install --global dotnet-ef

# Add the tools directory to the PATH
ENV PATH="$PATH:/root/.dotnet/tools"

# Run migrations for ApplicationContext
RUN dotnet ef database update --context ApplicationContext --project Emite.CCM.Infrastructure --startup-project Emite.CCM.Web

# Run migrations for IdentityContext
RUN dotnet ef database update --context IdentityContext --project Emite.CCM.Infrastructure --startup-project Emite.CCM.Web

# Stage 3: Use a smaller runtime image for the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .

# Install ping command
RUN apt-get update && apt-get install -y iputils-ping
RUN apt-get update && apt-get install -y telnet

# Expose HTTP and HTTPS ports
EXPOSE 8080
EXPOSE 443

# Copy the certificate (if applicable)
COPY ./certs/aspnetcore.pfx /https/aspnetcore.pfx

# Set environment variables for the certificate
ENV ASPNETCORE_Kestrel__Certificates__Default__Password "certpass123!@"
ENV ASPNETCORE_Kestrel__Certificates__Default__Path "/https/aspnetcore.pfx"
ENV SslCertificate__Path "/https/aspnetcore.pfx"
ENV SslCertificate__Password "certpass123!@#"

# Set the entry point for the container
ENTRYPOINT ["dotnet", "Emite.CCM.Web.dll"]
